server:
  error:
    include-message: always
    include-binding-errors: always
  domain: http://localhost:8080
gcp:
  storage:
    bucket:
      homeWork: java-academy-oct2022
      images: eng-avatar-images

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/english
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: inventorsoftenglish@gmail.com
    password: zqjanwkpkjjctsxs

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    jwt:
      secret: "someSecretKey"
      access_token_duration: 900_000
      refresh_token_duration: 18_000_000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

schedule:
  lesson-generator: "0 0 0 * * 7"
  interval-days: 7
